language: elixir

elixir:
  - 1.6
  - 1.7

otp_release:
  - 19.3
  - 20.3
  - 21.1

script:
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)
